-- MySQL Script generated by MySQL Workbench
-- 11/10/16 22:52:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema petstrap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petstrap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petstrap` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `petstrap` ;

-- -----------------------------------------------------
-- Table `petstrap`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petstrap`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NOT NULL,
  `texto` TEXT NOT NULL,
  `satisfacao` TINYINT NOT NULL,
  PRIMARY KEY (`id_comentario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petstrap`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petstrap`.`imagens` (
  `id_imagem` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `pasta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_imagem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petstrap`.`banners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petstrap`.`banners` (
  `id_imagem` INT NOT NULL,
  `posicao` TINYINT NOT NULL,
  `url` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_imagem`),
  CONSTRAINT `fk_banners_imagens`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `petstrap`.`imagens` (`id_imagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petstrap`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petstrap`.`produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NOT NULL,
  `descricao_reduzida` VARCHAR(140) NOT NULL,
  `valor` DECIMAL(10,0) NOT NULL,
  `descricao_detalhada` VARCHAR(240) NOT NULL,
  `id_imagem` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_produtos_imagens1_idx` (`id_imagem` ASC),
  CONSTRAINT `fk_produtos_imagens1`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `petstrap`.`imagens` (`id_imagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petstrap`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petstrap`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(75) NOT NULL,
  `nome` VARCHAR(75) NOT NULL,
  `senha` CHAR(32) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
